### ISSUE TITLE
Command triggers

### ISSUE THREAD

**Issue by Dragas** [BreadMoirai/BreadBotFramework#5]
Do not suggest using a common symbol (such as !, %, $, etc) as command triggers. This may overlap with other bots and in turn cause server wide chaos where 600 or so bots are replying to your command at once.

Instead you should suggest using mentions. This makes sure that only YOUR bot gets triggered.

**Comment by BreadMoirai** [comment]
let me make changes to the wiki. mentions are supported and the prefix is entirely up to whomever uses this library. by default it is set to the most common prefix but can be changed

**Comment by BreadMoirai** [comment]
https://github.com/BreadMoirai/BreadBotFramework/wiki/10)-Prefix
